
bank_loan_datasets:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: analytics-bank-loan
      dataset: staging
      location: asia-south1
      keyfile: C:\Users\hp\Downloads\analytics-bank-loan-cb577c1c6dea.json
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
  target: dev
