
bank_loan_datasets:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: your_project_url
      dataset: your_database or schema
      location: your_project_region
      keyfile: service_account_path
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
  target: dev
